--#region Imports
require("utils")

--#endregion

local ModName = "ScufflesMetalFarmCollection"
local Sn2ModSettingsDir = "./ue4ss/Mods/SN2ModSettings/"
local registrationsDir = Sn2ModSettingsDir .. "registrations/"
local thisModManifestPath = registrationsDir .. ModName .. ".lua"
local defaultOutputName = "%o"

local config = require("config")

local metalFarms = {}

local function log(msg)
    print(string.format("[%s] %s\n", ModName, msg))
end

--#region SN2ModSettings Config Foo

do    
    local manifest = [=[-- Auto-generated by ScufflesMetalFarmCollection. Do not edit; will be regenerated.
return {
    name        = "ScufflesMetalFarmCollection",
    version     = "1.0.0",
    author      = "Scuffle Kerfuffle",
    display     = "Scuffle's Metal Farm Collection",
    github      = "scufflekerfuffle/subnautica2mods/scufflesmetalfarmcollection",
    settings    = {
        { key="Enabled", title="Enable Automatic Metal Farm Collection",
            description="Master switch. When off, all metal farms will need to be collected manually.",
            type="toggle", default=true },
    },
}
]=]

    local enabledFile = io.open(Sn2ModSettingsDir .. "enabled.txt", "r")

    if not enabledFile then        
        log("SN2ModSettings not enabled. Manifest will not be written.")
        return
    end

    enabledFile:close()

    local attempts = 0
    local maxAttempts = 10

    local function tryWriteManifest()
        attempts = attempts + 1
        local sn2manifest = io.open(registrationsDir .. "SN2ModSettings.lua", "r")
        local initialized = sn2manifest ~= nil
        
        if sn2manifest then
            sn2manifest:close()
        end
        
        if initialized or attempts >= maxAttempts then
            if not initialized then
               CreateDirectory(registrationsDir)
            end
            if WriteText(thisModManifestPath, manifest) then
                log(string.format("Manifest written successfully (attempt %d/%d).\n", attempts, maxAttempts))
            end
        else
            -- Retry in 1 second
            ExecuteWithDelay(1000, function()
                ExecuteInGameThread(tryWriteManifest)
            end)
        end       
    end
    -- Start polling after 1 second (give SN2ModSettings time to begin loading)
    ExecuteWithDelay(1000, function()
        ExecuteInGameThread(tryWriteManifest)
    end)
end
--#endregion

--#region Farm Collection Logic

local function transferItems(farm, farmInventory)

    if not farm or not farm:IsValid() then
        return
    end

    if not farmInventory or not farmInventory:IsValid() then
        return
    end

    if not FindAllOf then
        log("FindAllOf function not found. Is ue4ss installed?")
        return
    end

    local locA = farm:K2_GetActorLocation()
    log(string.format("Transferring items from farm inventory at location (%.2f, %.2f, %.2f) to nearby lockers...", locA.X, locA.Y, locA.Z))
    
    local containerSource = { class = "SN2Locker", getInventory = function(locker) return locker.Inventory end, hasLabel = true}

    local targetLockers = {}

    local lockerActors = FindAllOf(containerSource.class)
    if not lockerActors then
        log("No Lockers found.")
        return
    end

    for _, lockerActor in ipairs(lockerActors) do
        if not lockerActor or not lockerActor:IsValid() then
            goto continue
        end

        local distance = GetDistance(farm, lockerActor)
        --look for lockers within 10000 unreal units (100 meters) that have a label starting with the default output name
        if distance and distance <= 10000 then
            local ok, inventory = pcall(function () return containerSource.getInventory(lockerActor) end)

            if ok and inventory and inventory:IsValid() then
                local rawLabel = nil
                --NOTE: This differs from how QuickSort behaves due to having only the one type of source.
                local ok2, label = pcall(function() return GetActorLabel(lockerActor) end)

                if ok2 and label then
                    rawLabel = label
                end

                if rawLabel and rawLabel:sub(1, #defaultOutputName) == defaultOutputName then
                    
                    local okMax, maxItems = pcall(function() return inventory.MaxItems end)
                    local okItems, items = pcall(function() return inventory:GetItems() end)

                    if not okMax or not maxItems or not okItems or not items then
                        goto continue
                    end

                    local currentItemCount = #items

                    if currentItemCount < maxItems then
                        table.insert(targetLockers, {inventory = inventory, inventoryid = inventory.InventoryId,label = rawLabel, currentItemCount = currentItemCount, maxItems = maxItems})
                    end
                end
            end
        end
        ::continue::
    end

    if #targetLockers <=0 then
        log("No valid target lockers found near farm.")
        return
    end

    local ok, itemsToTransfer = pcall(function() return farmInventory:GetItems() end)

    if not ok or not itemsToTransfer then
        log(string.format("Error accessing farm inventory items. ok: %b, not itemsToTransfer: %b", ok, not itemsToTransfer))
        return
    end

    for _, rawItem in ipairs(itemsToTransfer) do
        local innerItem = rawItem:get()

        for _, locker in ipairs(targetLockers) do
            if locker.currentItemCount >= locker.maxItems then
                goto lockerContinue
            end

            local okTransfer, err = pcall(function() return farmInventory:MoveItemBetweenInventories(innerItem.ItemId, farmInventory.InventoryId, locker.inventory.Inventory) end)

            if not okTransfer then
                log("Error transferring item: " .. tostring(err))
            else
                locker.currentItemCount = locker.currentItemCount + 1
                break
            end
            ::lockerContinue::
        end
        ::continue::
    end
end

local function CollectAllFarms()
    log("Collecting metal farms...")
    if not FindAllOf then
        log("FindAllOf function not found. Is ue4ss installed?")
        return
    end

    local farms = FindAllOf("SN2MetalFarm")

    if not farms then
        log("No metal farms found.")
        return
    end

    for _, farm in ipairs(farms) do
        if not farm or not farm:IsValid() then
            log("Invalid farm found. Skipping...")
            goto continue
        end

        local growers = farm.SeedGrowerComponents
        
        if not growers or #growers == 0 then
            log("No SeedGrowerComponents found for farm. Skipping...")
            goto continue
        end

        for i = 1, #growers do
            local grower = growers[i]            
            if grower and grower:IsValid() and grower.HasFullyRipenedSeed() then
                local locA = farm:K2_GetActorLocation()
                log(string.format("Starting collection check for farm at location (%.2f, %.2f, %.2f)", locA.X, locA.Y, locA.Z))
                --local harvestAmount = grower.GetRipenedAmount()

                --if harvestAmount and harvestAmount > 0 then                    
                --end
                local inventory = farm.InventoryComponent

                if inventory and inventory:IsValid() then
                    transferItems(farm, inventory)
                else
                    log(string.format("No valid inventory found for farm at location (%.2f, %.2f, %.2f). Skipping...", locA.X, locA.Y, locA.Z))
                end
            end
        end

        ::continue::
    end
end

LoopAsync(1000, function()
    log("Beginning metal farm collection process...")
    if not ModRef then
            log("ModRef not found. Is this being run in the context of a ue4ss mod?")
        return
    end

    for k, currentPair in pairs(config) do
        local sharedVariable = ModRef:GetSharedVariable("SN2ModSettings/" .. ModName .. "/" .. k)
        
        if sharedVariable ~= nil and type(sharedVariable) == type(currentPair) and sharedVariable ~= currentPair then
            config[k] = sharedVariable
        end
    end

    if config.Enabled then
        log("Automatic collection enabled. Collecting farms...")
        ExecuteInGameThread(CollectAllFarms)
    else
        log("Automatic collection disabled. Set 'Enabled' to true in SN2ModSettings to enable.")
    end
end
)

--#endregion