--#region Imports
require("utils")

--#endregion

local ModName = "ScufflesMetalFarmCollection"
local Sn2ModSettingsDir = "./ue4ss/Mods/SN2ModSettings/"
local registrationsDir = Sn2ModSettingsDir .. "registrations/"
local thisModManifestPath = registrationsDir .. ModName .. ".lua"
local defaultOutputName = "%o"

local config = require("config")

local metalFarms = {}
local lockersWithCorrectLabel = {}

local function log(msg)
    print(string.format("[%s] %s\n", ModName, msg))
end

--#region SN2ModSettings Config Foo

do    
    local manifest = [=[-- Auto-generated by ScufflesMetalFarmCollection. Do not edit; will be regenerated.
return {
    name        = "ScufflesMetalFarmCollection",
    version     = "1.0.0",
    author      = "Scuffle Kerfuffle",
    display     = "Scuffle's Metal Farm Collection",
    github      = "scufflekerfuffle/subnautica2mods/scufflesmetalfarmcollection",
    settings    = {
        { key="Enabled", title="Enable Automatic Metal Farm Collection",
            description="Master switch. When off, all metal farms will need to be collected manually.",
            type="toggle", default=true },
    },
}
]=]

    local enabledFile = io.open(Sn2ModSettingsDir .. "enabled.txt", "r")

    if not enabledFile then        
        log("SN2ModSettings not enabled. Manifest will not be written.")
        return
    end

    enabledFile:close()

    local attempts = 0
    local maxAttempts = 10

    local function tryWriteManifest()
        attempts = attempts + 1
        local sn2manifest = io.open(registrationsDir .. "SN2ModSettings.lua", "r")
        local initialized = sn2manifest ~= nil
        
        if sn2manifest then
            sn2manifest:close()
        end
        
        if initialized or attempts >= maxAttempts then
            if not initialized then
               CreateDirectory(registrationsDir)
            end
            if WriteText(thisModManifestPath, manifest) then
                log(string.format("Manifest written successfully (attempt %d/%d).\n", attempts, maxAttempts))
            end
        else
            -- Retry in 1 second
            ExecuteWithDelay(1000, function()
                ExecuteInGameThread(tryWriteManifest)
            end)
        end       
    end
    -- Start polling after 1 second (give SN2ModSettings time to begin loading)
    ExecuteWithDelay(1000, function()
        ExecuteInGameThread(tryWriteManifest)
    end)
end
--#endregion

--#region Farm Collection Logic

local function GetSeedItem(farmInventory)
    if not farmInventory or not farmInventory:IsValid() then
        return nil
    end

    local okItems, itemsToTransfer = pcall(function() return farmInventory:GetItems() end)

    if not okItems or not itemsToTransfer or #itemsToTransfer == 0 then
        return nil
    end
    
    local seedItem = itemsToTransfer[1]:get()

    if not seedItem or not seedItem:IsValid() then
        return nil
    end

    return seedItem
end

local function ResetFarm(farmInventory, seedItem)
    if not farmInventory or not farmInventory:IsValid() then
        return false
    end

    farmInventory:RemoveItemTypeFromInventory(seedItem.ItemType, 1)
    farmInventory:AddItemTypeToInventory(seedItem.ItemType, 1)
end

local function transferItems(farm, farmInventory)

    if not farm or not farm:IsValid() or not farmInventory or not farmInventory:IsValid() or not FindAllOf then
        return false
    end

    if #lockersWithCorrectLabel <=0 then
        log("No valid target lockers found with the correct label.")
        return false
    end

    local ok, itemsToTransfer = pcall(function() return farmInventory:GetItems() end)

    if not ok or not itemsToTransfer then
        log(string.format("Error accessing farm inventory items. ok: %b, not itemsToTransfer: %b", ok, not itemsToTransfer))
        return false
    end

    for _, rawItem in ipairs(itemsToTransfer) do
        local innerItem = rawItem:get()
        
        if not innerItem or not innerItem:IsValid() then
            log("Invalid item found in farm inventory. Skipping item.")
            goto continue
        end
        --[[
        --This block is for logging and we don't need it all the time.
        if innerItem.ItemType then
            local innerItemTypeOk, innerItemTypeName = pcall(function() return innerItem.ItemType:GetFName():ToString() end)
            if innerItemTypeOk and innerItemTypeName then
                log(string.format("Found item in farm inner inventory: %s", innerItemTypeName))
            end
        end
        ]]

        for _, locker in ipairs(lockersWithCorrectLabel) do
            if locker.currentItemCount >= locker.maxItems then
                goto lockerContinue
            end

            -- MoveItemBetweenInventories doesn't error out, but it still fails to transfer the item. We will need to try another transfer mechanism.
            
            local okTransfer, err = pcall(function() return farmInventory:MoveItemBetweenInventories(innerItem.ItemId, innerItem.InventoryId, locker.inventoryid) end)

            if not okTransfer then
                log("Error transferring item: " .. tostring(err))
            else
                locker.currentItemCount = locker.currentItemCount + 1

                local displayName = nil

                pcall(function() displayName = innerItem.ItemType.Name:ToString() end)

                if displayName then
                    log(string.format("Transferred item '%s' to locker '%s'. Current count: %d/%d", displayName, locker.label, locker.currentItemCount, locker.maxItems))
                end
                break
            end
            
            ::lockerContinue::
        end
        ::continue::
    end
    return true
end

local function AddSeedItemsToLockers(seedItem)
    if not seedItem or not seedItem:IsValid() then
        return false
    end

    for _, locker in ipairs(lockersWithCorrectLabel) do
        if locker.currentItemCount >= locker.maxItems then
            goto lockerContinue
        end

        local ok = pcall(function() return locker.inventory:AddItemTypeToInventory(seedItem.ItemType, 1) end)

        if ok then
            log(string.format("Added seed item '%s' to locker '%s' during collection. Current count: %d/%d", seedItem.ItemType.Name:ToString(), locker.label, locker.currentItemCount + 1, locker.maxItems))
            break
        else
            log(string.format("Error adding seed item '%s' to locker '%s' during collection.", seedItem.ItemType.Name:ToString(), locker.label))            
            break
        end
        
        ::lockerContinue::
    end
end

local function CollectFarm(farm)
    if not farm or not farm:IsValid() then
        return
    end

    local growers = farm.SeedGrowerComponents
    
    if not growers or #growers == 0 then
        return
    end

    for i = 1, #growers do
        local grower = growers[i]            
        if grower and grower:IsValid() and grower.HasFullyRipenedSeed() then
            local inventory = farm.InventoryComponent

            if inventory and inventory:IsValid() then
                local seedItem = GetSeedItem(inventory)

                if not seedItem then
                    log("No seed item found in farm inventory. Skipping collection for this grower.")
                    break
                end

                transferItems(farm, inventory)
                AddSeedItemsToLockers(seedItem)
                local farmAddOk = pcall(function() return inventory:AddItemTypeToInventory(seedItem.ItemType, 1) end)
                if not farmAddOk then
                    log("Error adding seed item back to farm inventory after collection.")
                end
                
            end
        end
    end
end

local function CollectAllFarms()
    if not metalFarms or #metalFarms == 0 then
        return
    end

    for _, farm in ipairs(metalFarms) do
        CollectFarm(farm)
    end
end

local function RegisterFarms()
    if not FindAllOf then
        log("FindAllOf function not found. Is ue4ss installed?")
        return
    end

    log("Registering metal farms...")
    
    --reset metalFarms to ensure we don't keep duplicates if this function is called multiple times for some reason
    metalFarms = {}

    local foundFarms = FindAllOf("SN2MetalFarm")
   
    if not foundFarms or #foundFarms == 0 then
        log("No metal farms found.")
        return
    end

    for _, farm in ipairs(foundFarms) do
        if not farm or not farm:IsValid() then
            log("Invalid farm found. Skipping...")
            goto continue
        end

        --metalFarms[#metalFarms + 1] = farm

        table.insert(metalFarms, farm)
        local locA = farm:K2_GetActorLocation()
        log(string.format("Registered metal farm at location (%.2f, %.2f, %.2f)", locA.X, locA.Y, locA.Z))
        
        ::continue::
    end
end

local function RegisterLockers()
    local containerSource = { class = "SN2Locker", getInventory = function(locker) return locker.Inventory end, hasLabel = true}

    --Clear lockersWithCorrectLabel to ensure we don't keep duplicates if this function is called multiple times for some reason
    lockersWithCorrectLabel = {}

    local lockerActors = FindAllOf(containerSource.class)

    if not lockerActors then
        log("No Lockers found.")
        return
    end

    for _, lockerActor in ipairs(lockerActors) do
        if not lockerActor or not lockerActor:IsValid() then
            log("Invalid locker found. Skipping...")
            goto continue
        end

        local ok, inventory = pcall(function () return containerSource.getInventory(lockerActor) end)

        if not ok or not inventory or not inventory:IsValid() then
            log("Error accessing locker inventory. Skipping locker.")
            goto continue
        end
        
        local rawLabel = nil
        --NOTE: This differs from how QuickSort behaves due to having only the one type of source.
        local ok2, label = pcall(function() return GetActorLabel(lockerActor) end)

        if ok2 and label then
            rawLabel = label
        else
            log("Error accessing locker label. Skipping locker.")
            goto continue
        end

        if IsNilOrEmpty(rawLabel) then
            log("Locker label is nil. Skipping locker.")
            goto continue
        end

        if rawLabel:sub(1, #defaultOutputName) ~= defaultOutputName then
            log(string.format("Locker label '%s' does not start with default output name '%s'. Skipping locker.", rawLabel, defaultOutputName))
            goto continue
        end

        local okItemCount, inventoryItems = pcall(function() return lockerActor.inventory:GetItems() end)
        
        if not okItemCount or not inventoryItems then
            log("Error accessing locker inventory items. Skipping locker.")
            goto continue
        end

        local okMaxItems, maxItems = pcall(function() return lockerActor.inventory.MaxItems end)

        if not okMaxItems or not maxItems then
            log("Error accessing locker inventory max items. Skipping locker.")
            goto continue
        end

        table.insert(lockersWithCorrectLabel, {inventory = inventory, inventoryid = inventory.InventoryId,label = rawLabel, currentItemCount = #inventoryItems, maxItems = maxItems})
        
        
        local locA = lockerActor:K2_GetActorLocation()
        log(string.format("Registered locker at location (%.2f, %.2f, %.2f)", locA.X, locA.Y, locA.Z))
        
        ::continue::
    end

end

RegisterHook("/Script/Engine.PlayerController:ClientRestart", function()
    ExecuteWithDelay(3000, function()
        RegisterFarms()
        RegisterLockers()
    end)
end)

RegisterHook("/Script/Engine.Actor:K2_DestroyActor", function(Context)
    local destroyedActor = Context:get()

    if not destroyedActor or not destroyedActor:IsValid() then
        return
    end

    for i, farm in ipairs(metalFarms) do
        if farm == destroyedActor then
            log(string.format("Metal farm at location (%.2f, %.2f, %.2f) was destroyed. Removing from collection.", farm:K2_GetActorLocation().X, farm:K2_GetActorLocation().Y, farm:K2_GetActorLocation().Z))
            table.remove(metalFarms, i)
            break
        end
    end
end)

RegisterHook("/Script/UMG.EditableText:SetText", function(Context, Params)
    local signComponent = Context:get()
    local lockerActor = signComponent:GetOwner()
    
    -- Params.NewText contains the FText structure submitted by the player
    local newTextString = Params.NewText:get():ToString()
    local oldTextString = Params.OldText:get():ToString()
    
    -- Ensure we are dealing with a locker (filters out signs, beacons, beacons etc.)
    if lockerActor then
        local actorName = lockerActor:GetClass():GetName()
        if string.find(actorName, "Locker") then
            log(string.format("Sign text changed on actor '%s'. Old text: '%s', New text: '%s'", lockerActor:GetName(), oldTextString, newTextString))
            RegisterLockers() -- Re-register lockers to update our list of valid targets based on the new label text
        end
    end
end)

NotifyOnNewObject("/Game/Blueprints/Farming/BP_MetalFarm.BP_MetalFarm_C", function(NewObject)
    ExecuteWithDelay(100,function()
        RegisterFarms()
    end)
end)

-- NotifyOnNewObject("/Game/Blueprints/World/ResourceDeposits/BP_Resource_MetalFarmSeed.BP_Resource_MetalFarmSeed_C", function(NewObject)
--     ExecuteWithDelay(100,function()
--         RegisterFarms()
--     end)
-- end)

--[[
LoopAsync(1000, function()
    if not ModRef then
        return
    end

    for k, currentPair in pairs(config) do
        local sharedVariable = ModRef:GetSharedVariable("SN2ModSettings/" .. ModName .. "/" .. k)
        
        if sharedVariable ~= nil and type(sharedVariable) == type(currentPair) and sharedVariable ~= currentPair then
            config[k] = sharedVariable
        end
    end

    if config.Enabled then
        ExecuteInGameThread(CollectAllFarms)
    end
end
)
]]--
local function RunUsingDelay()
    if config.Enabled then
        ExecuteInGameThread(CollectAllFarms)
    end
    ExecuteWithDelay(1000, RunUsingDelay) -- Schedule the next execution after 1 second
end

RunUsingDelay() -- Start the loop
--#endregion