--#region Imports

require("utils")

--#endregion

--#region Constants and Variables

local ModName = "ScufflesMetalFarmCollection"
local Sn2ModSettingsDir = "./ue4ss/Mods/SN2ModSettings/"
local registrationsDir = Sn2ModSettingsDir .. "registrations/"
local thisModManifestPath = registrationsDir .. ModName .. ".lua"
local defaultOutputName = "%o"

local config = require("config")

local containerSource = { class = "SN2Locker", getInventory = function(locker) return locker.Inventory end, hasLabel = true}
local metalFarms = {}
local lockersWithCorrectLabel = {}

--#endregion

--#region SN2ModSettings Config Foo

do
    local manifest = [=[-- Auto-generated by ScufflesMetalFarmCollection. Do not edit; will be regenerated.
return {
    name        = "ScufflesMetalFarmCollection",
    version     = "1.0.0",
    author      = "Scuffle Kerfuffle",
    display     = "Scuffle's Metal Farm Collection",
    github      = "scufflekerfuffle/subnautica2mods/scufflesmetalfarmcollection",
    settings    = {
        { key="Enabled", title="Enable Automatic Metal Farm Collection",
            description="Master switch. When off, all metal farms will need to be collected manually.",
            type="toggle", default=true },
    },
}
]=]

    local enabledFile = io.open(Sn2ModSettingsDir .. "enabled.txt", "r")

    if not enabledFile then
        Log("SN2ModSettings not enabled. Manifest will not be written.")
        return
    end

    enabledFile:close()

    local attempts = 0
    local maxAttempts = 10

    local function tryWriteManifest()
        attempts = attempts + 1
        local sn2manifest = io.open(registrationsDir .. "SN2ModSettings.lua", "r")
        local initialized = sn2manifest ~= nil

        if sn2manifest then
            sn2manifest:close()
        end

        if initialized or attempts >= maxAttempts then
            if not initialized then
               CreateDirectory(registrationsDir)
            end
            if WriteText(thisModManifestPath, manifest) then
                Log(string.format("Manifest written successfully (attempt %d/%d).\n", attempts, maxAttempts))
            end
        else
            -- Retry in 1 second
            ExecuteWithDelay(1000, function()
                ExecuteInGameThread(tryWriteManifest)
            end)
        end
    end
    -- Start polling after 1 second (give SN2ModSettings time to begin loading)
    ExecuteWithDelay(1000, function()
        ExecuteInGameThread(tryWriteManifest)
    end)
end
--#endregion

--#region Actor Registrations

local function RegisterFarm(farm)
    if not farm or not farm:IsValid() then
        return
    end

    table.insert(metalFarms, farm)
end

local function RegisterFarms()
    if not FindAllOf then
        Log("FindAllOf function not found. Is ue4ss installed?")
        return
    end

    --reset metalFarms to ensure we don't keep duplicates if this function is called multiple times for some reason
    metalFarms = {}

    local foundFarms = FindAllOf("SN2MetalFarm")

    if not foundFarms or #foundFarms == 0 then
        return
    end

    for _, farm in ipairs(foundFarms) do
        RegisterFarm(farm)
    end
end

--Handles registering a given locker.
--NOTE: This differs from how QuickSort behaves due to having only the one type of source.
local function RegisterLocker(lockerActor)
    if not lockerActor or not lockerActor:IsValid() then
            Log("Invalid locker found. Skipping...")
            return
        end

        local okInventory, inventory = pcall(function () return containerSource.getInventory(lockerActor) end)

        if not okInventory or not inventory or not inventory:IsValid() then
            return
        end

        local rawLabel = nil

        local okLabel, label = pcall(function() return GetActorLabel(lockerActor) end)

        if okLabel and label then
            rawLabel = label
        else
            return
        end

        if IsNilOrEmpty(rawLabel) then
            return
        end

        if rawLabel:sub(1, #defaultOutputName) ~= defaultOutputName then
            return
        end

        local okItemCount, inventoryItems = pcall(function() return lockerActor.inventory:GetItems() end)

        if not okItemCount or not inventoryItems then
            return
        end

        local okMaxItems, maxItems = pcall(function() return lockerActor.inventory.MaxItems end)

        if not okMaxItems or not maxItems then
            return
        end

        local okFullName, fullName = pcall(function() return lockerActor:GetFullName() end)

        if not okFullName or not fullName then
            return
        end

        table.insert(lockersWithCorrectLabel, {fullName = fullName, inventory = inventory, inventoryid = inventory.InventoryId,label = rawLabel, currentItemCount = #inventoryItems, maxItems = maxItems})
end

--Finds and attempts to register every locker (via containerSource) in the world. Only lockers with the correct label format will be registered.
--If we want other kinds of containers (such as tailing chests), we can extend this function in the future by adding new container sources.
local function RegisterLockers()
    --Clear lockersWithCorrectLabel to ensure we don't keep duplicates if this function is called multiple times for some reason
    lockersWithCorrectLabel = {}

    local lockerActors = FindAllOf(containerSource.class)

    if not lockerActors then
        return
    end

    for _, lockerActor in ipairs(lockerActors) do
        RegisterLocker(lockerActor)
    end
end

--#endregion

--#region Farm Collection Logic

--Looks into the Metal Farm's inventory for the seed item, and returns it if found.
local function GetSeedItem(farmInventory)
    if not farmInventory or not farmInventory:IsValid() then
        return nil
    end

    local okItems, itemsToTransfer = pcall(function() return farmInventory:GetItems() end)

    if not okItems or not itemsToTransfer or #itemsToTransfer == 0 then
        return nil
    end

    --Metal Farms only have the one item in them, so we're grabbing that for the transfer.
    local seedItem = itemsToTransfer[1]:get()

    if not seedItem or not seedItem:IsValid() then
        return nil
    end

    return seedItem
end

--Part 1 of 2 for the automated collection process. Transfer the seed item from the metal farm to the locker. 
--This clears the farm out as if the user had manually removed the seed item from the farm, which allows the grower 
--to start growing a new seed right away without us having to worry about trying to manipulate the grower's state or timers.
local function TransferSeedToLocker(farm, farmInventory)

    if not farm or not farm:IsValid() or not farmInventory or not farmInventory:IsValid() or not FindAllOf then
        return false
    end

    if #lockersWithCorrectLabel <=0 then
        --Log("No valid target lockers found with the correct label.")
        return false
    end

    local okItems, itemsToTransfer = pcall(function() return farmInventory:GetItems() end)

    if not okItems or not itemsToTransfer then
        Log(string.format("Error accessing farm inventory items. ok: %b, not itemsToTransfer: %b", okItems, not itemsToTransfer))
        return false
    end

    for _, rawItem in ipairs(itemsToTransfer) do
        local innerItem = rawItem:get()
        
        if not innerItem or not innerItem:IsValid() then
            --Log("Invalid item found in farm inventory. Skipping item.")
            goto continue
        end
        --[[
        --This block is for logging and we don't need it all the time.
        if innerItem.ItemType then
            local innerItemTypeOk, innerItemTypeName = pcall(function() return innerItem.ItemType:GetFName():ToString() end)
            if innerItemTypeOk and innerItemTypeName then
                log(string.format("Found item in farm inner inventory: %s", innerItemTypeName))
            end
        end
        ]]

        for _, locker in ipairs(lockersWithCorrectLabel) do
            if locker.currentItemCount >= locker.maxItems then
                goto lockerContinue
            end

            local okTransfer, err = pcall(function() return farmInventory:MoveItemBetweenInventories(innerItem.ItemId, innerItem.InventoryId, locker.inventoryid) end)

            if not okTransfer then
                Log("Error transferring item: " .. tostring(err))
            else
                locker.currentItemCount = locker.currentItemCount + 1
                --[[This section is for logging and we don't need it all the time.
                local displayName = nil

                pcall(function() displayName = innerItem.ItemType.Name:ToString() end)

                if displayName then
                    Log(string.format("Transferred item '%s' to locker '%s'. Current count: %d/%d", displayName, locker.label, locker.currentItemCount, locker.maxItems))
                end
                ]]--
                break
            end
            
            ::lockerContinue::
        end
        ::continue::
    end
    return true
end

--Part 2 of 2 for the automated collection process. After transferring the seed item to the locker, we add a new seed item to 
--the locker to simulate what would happen if the user had manually harvested the metal farm and then added both "grown" items 
--to the locker themselves. Future state may include allowing more than 2 at a time (the transfer and this single new item)
local function CreateSeedInLocker(seedItem)
    if not seedItem or not seedItem:IsValid() then
        return false
    end

    for _, locker in ipairs(lockersWithCorrectLabel) do
        if locker.currentItemCount >= locker.maxItems then
            goto lockerContinue
        end

        local ok = pcall(function() return locker.inventory:AddItemTypeToInventory(seedItem.ItemType, 1) end)

        if ok then
            --Log(string.format("Added seed item '%s' to locker '%s' during collection. Current count: %d/%d", seedItem.ItemType.Name:ToString(), locker.label, locker.currentItemCount + 1, locker.maxItems))
            break
        else
            Log(string.format("Error adding seed item '%s' to locker '%s' during collection.", seedItem.ItemType.Name:ToString(), locker.label))            
            break
        end

        ::lockerContinue::
    end
end

--The marshalling logic calls the above functions in sequence to complete the collection process for a given farm.
--This version of the mod finds a new locker for each step (TransferSeedToLocker and CreateSeedInLocker)
--Future versions will do both in the same locker if it has enough space. That logic is more complex,
--so we're going with the simple version first since it works.
local function CollectFarm(farm)
    if not farm or not farm:IsValid() then
        return
    end

    local growers = farm.SeedGrowerComponents

    if not growers or not growers:IsValid() or #growers == 0 then
        return
    end

    for i = 1, #growers do
        local grower = growers[i]
        if grower and grower:IsValid() and grower.HasFullyRipenedSeed() then
            local inventory = farm.InventoryComponent

            if inventory and inventory:IsValid() then
                local seedItem = GetSeedItem(inventory)

                if not seedItem then
                    --Log("No seed item found in farm inventory. Skipping collection for this grower.")
                    break
                end

                TransferSeedToLocker(farm, inventory)
                CreateSeedInLocker(seedItem)
                local farmAddOk = pcall(function() return inventory:AddItemTypeToInventory(seedItem.ItemType, 1) end)
                if not farmAddOk then
                    Log("Error adding seed item back to farm inventory after collection.")
                end
            end
        end
    end
end

--Goes through the registered farms and attempts to collect from each of them by calling CollectFarm.
local function CollectAllFarms()
    if not metalFarms or #metalFarms == 0 then
        return
    end

    for _, farm in ipairs(metalFarms) do
        CollectFarm(farm)
    end
end

--#endregion

--#region Handler Methods

--This does get called whenever the builder tool is destroying something, but it's necessary 
--to catch when a farm or locker is destroyed so we can remove it from our collections and 
--avoid trying to interact with invalid actors.
local function OnBuilderTargetDestroyed(Tool, Target)
    local targetActor = Target:get()

    if not targetActor or not targetActor:IsValid() then
        return
    end

    local targetFullName = targetActor:GetFullName()

    --Note for the next version: Maybe we can determine whether the passed-in actor is a farm or locker before looping through both collections? 
    --Would save some cycles, but it's a bit more complex to implement.
    for i, farm in ipairs(metalFarms) do
        local farmFullName = farm:GetFullName()

        if farmFullName == targetFullName then
            table.remove(metalFarms, i)
            return
        end
    end

    for i, locker in ipairs(lockersWithCorrectLabel) do
        local lockerFullName = locker.fullName

        if lockerFullName == targetFullName then
            table.remove(lockersWithCorrectLabel, i)
            return
        end
    end
end

--This is intended to catch when a game starts or is loaded.
--The delayed start is to give the farms and lockers a chance to load in.
--Need to test whether this is still needed. OnNewObject notifications
--might catch this now.
local function OnClientRestart()
    ExecuteWithDelay(3000, function()
        RegisterFarms()
        RegisterLockers()
    end)
end

--This is intended to catch when a new locker is created OR when an existing locker is partially deconstructed and then 
--reconstructed. In both cases, we want to check if the locker is valid and add it to our collection if so.
--Note for Posterity: As of the first release of SN2, Lockers do not keep their labels
--when they are partially deconstructed and then reconstructed. This means that a newly-reconstructed
--locker will never be a viable target, but if that ever changes, this will still handle it.
local function OnLockerCreated(lockerActor)
    RegisterLocker(lockerActor)
end

--This is intended to catch when a new metal farm is created, so we can add it to our collection and start collecting from it.
local function OnMetalFarmCreated(metalFarmActor)
    RegisterFarm(metalFarmActor)
end

local function OnSeedAdded(farmActor, inventoryItem)
    local farm = farmActor:get()
    local lInventory = inventoryItem:get()

    if not farm or not farm:IsValid() or not lInventory or not lInventory:IsValid() then
        return
    end

    if not metalFarms or #metalFarms == 0 then
        metalFarms = {farm}
        return
    else
        for _, registeredFarm in ipairs(metalFarms) do
            if registeredFarm:GetFullName() == farm:GetFullName() then
                return
            end
        end

        table.insert(metalFarms, farm)
    end
end

local function OnSeedRemoved(farmActor, inventoryItem)
    local farm = farmActor:get()
    local lInventory = inventoryItem:get()

    if not farm or not farm:IsValid() or not lInventory or not lInventory:IsValid() then
        return
    end

    if not metalFarms or #metalFarms == 0 then
        return
    else
        for i, registeredFarm in ipairs(metalFarms) do
            if registeredFarm:GetFullName() == farm:GetFullName() then
                table.remove(metalFarms, i)
                return
            end
        end
    end

end

--This is intended to catch when a locker label is changed, so we can update our list of valid lockers to transfer to based on the new label text.
local function OnTextChanged(Context, Params)
    --Note for the future; maybe dig into the passed-in parameters to see
    --if we can use the actual locker and (un)register it directly. This
    --uses a lot of cycles in really large games.
        ExecuteWithDelay(100,function()
            RegisterLockers()
        end)
end

--#endregion

--region Initialization and Loop
local function RunUsingDelay()
    if config.Enabled then
        ExecuteInGameThread(CollectAllFarms)
    end
    ExecuteWithDelay(2000, RunUsingDelay) -- Schedule the next execution after 2 seconds. Going with this to halve the number of calls, but still collect in a reasonable timeframe.
end

--Register all hooks and notifications
RegisterHook("/Script/Engine.PlayerController:ClientRestart", OnClientRestart)
RegisterHook("/Script/Subnautica2.SN2BuilderTool:OnTargetDestroyed", OnBuilderTargetDestroyed)
RegisterHook("/Script/Subnautica2.SN2MetalFarm:OnSeedAdded", OnSeedAdded)
RegisterHook("/Script/Subnautica2.SN2MetalFarm:OnSeedRemoved", OnSeedRemoved)
RegisterHook("/Script/UWEUserGeneratedContent.UWEUGCComponent:ServerSetPlayerText", OnTextChanged)


NotifyOnNewObject("/Script/Subnautica2.SN2MetalFarm", OnMetalFarmCreated)
NotifyOnNewObject("/Script/Subnautica2.SN2Locker", OnLockerCreated)

-- Start the loop
RunUsingDelay()

--#endregion